# Generated by Django 3.2.5 on 2021-11-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_proffessor',
            new_name='is_professor',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='branch',
            field=models.CharField(choices=[('cse', 'CSE'), ('eee', 'EEE'), ('ece', 'ECE'), ('mec', 'MECHANICAL'), ('civ', 'CIVIL'), ('bce', 'BIOTECH'), ('phe', 'PHARMA'), ('mat', 'MNC'), ('ALL', 'ALL')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='branch',
            field=models.CharField(choices=[('cse', 'CSE'), ('eee', 'EEE'), ('ece', 'ECE'), ('mec', 'MECH'), ('civ', 'CIVIL'), ('bce', 'BIOTECH'), ('phe', 'PHARMA'), ('mat', 'MNC')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.CharField(choices=[('cse', 'CSE'), ('eee', 'EEE'), ('ece', 'ECE'), ('mec', 'MECH'), ('civ', 'CIVIL'), ('bce', 'BIOTECH'), ('phe', 'PHARMA'), ('mat', 'MNC')], default=False, max_length=20),
        ),
    ]
